### ISSUE TITLE
Remove redundant parenthesis

### ISSUE THREAD

**Issue by nermine-ali** [Benjamin-coder1/IN104_Jonas_Benhamou_Tibi_Benjamin#3]
https://github.com/Benjamin-coder1/IN104_Jonas_Benhamou_Tibi_Benjamin/blob/774c65f7c4c2959aa6567b8e3fb305a72c34bc34/OOP/vivant.py#L24

**Comment by JonasBenhamou** [comment]
la supression des parentheses est faite
