### ISSUE TITLE
Missing self

### ISSUE THREAD

**Issue by nermine-ali** [Benjamin-coder1/IN104_Jonas_Benhamou_Tibi_Benjamin#4]
Missing `self.` before age, poids & taille, exp: `self.age`
https://github.com/Benjamin-coder1/IN104_Jonas_Benhamou_Tibi_Benjamin/blob/774c65f7c4c2959aa6567b8e3fb305a72c34bc34/TD2/a.py#L9

**Comment by JonasBenhamou** [comment]
Le bug est corrigé
