### ISSUE TITLE
Is it TD2 or TD3?

### ISSUE THREAD

**Issue by nermine-ali** [Benjamin-coder1/IN104_Jonas_Benhamou_Tibi_Benjamin#5]
TD2 is OOP intended for creating classes and methods.
TD3 is TDD intended to create unittest to test the classes created in TD2.

This part of the code have nothing to do with unittesting.
https://github.com/Benjamin-coder1/IN104_Jonas_Benhamou_Tibi_Benjamin/blob/774c65f7c4c2959aa6567b8e3fb305a72c34bc34/OOP/vivant.py#L52

**Comment by JonasBenhamou** [comment]
Nous avons résolu ce point
